rails/decidim/decidim-admin/config/routes.rb
# frozen_string_literal: true

Decidim::Admin::Engine.routes.draw do
  constraints(->(request) { Decidim::Admin::OrganizationDashboardConstraint.new(request).matches? }) do
    resource :organization, only: [:edit, :update], controller: "organization" do
      resource :appearance, only: [:edit, :update], controller: "organization_appearance"
      resource :homepage, only: [:edit, :update], controller: "organization_homepage" do
        resources :content_blocks, only: [:edit, :update], controller: "organization_homepage_content_blocks"
      end

      member do
        get :users
      end
    end

    Decidim.participatory_space_manifests.each do |manifest|
      mount manifest.context(:admin).engine, at: "/", as: "decidim_admin_#{manifest.name}"
    end

    resources :static_pages
    resources :static_page_topics, except: [:index]
    resources :scope_types, except: [:show]
    resources :scopes, except: [:show] do
      resources :scopes, except: [:show]
    end
    resources :metrics, only: [:index]
    resources :logs, only: [:index]
    resources :area_types, except: [:show]
    resources :areas, except: [:show]

    resources :authorization_workflows, only: :index

    Decidim.authorization_admin_engines.each do |manifest|
      mount manifest.admin_engine, at: "/#{manifest.name}", as: "decidim_admin_#{manifest.name}"
    end

    resources :users, except: [:edit, :update], controller: "users" do
      member do
        post :resend_invitation, to: "users#resend_invitation"
      end
      resource :block, only: [:new, :create, :destroy], controller: :block_user
    end

    resources :officializations, only: [:new, :create, :index, :destroy], param: :user_id do
      member do
        get :show_email
      end
    end

    resources :moderated_users, only: [:index] do
      member do
        put :ignore
      end
    end

    resources :impersonatable_users, only: [:index] do
      resources :promotions, controller: "managed_users/promotions", only: [:new, :create]
      resources :impersonation_logs, controller: "managed_users/impersonation_logs", only: [:index]
      resources :impersonations, controller: "impersonations", only: [:new, :create] do
        collection do
          post :close_session
        end
      end
    end

    resources :newsletter_templates, only: [:index, :show] do
      resources :newsletters, only: [:new, :create]

      member do
        get :preview
      end
    end

    resources :newsletters, except: [:new, :create] do
      member do
        get :recipients_count
        get :preview
        get :select_recipients_to_deliver
        post :deliver
      end
    end

    resources :user_groups, only: [:index] do
      member do
        put :verify
        put :reject
      end
      collection do
        resource :user_groups_csv_verification, only: [:new, :create], path: "csv_verification"
      end
    end

    resource :help_sections, only: [:show, :update]

    namespace :admin_terms do
      get :show
      put :accept
    end

    resources :share_tokens, only: :destroy

    resources :moderations, controller: "global_moderations" do
      member do
        put :unreport
        put :hide
        put :unhide
      end
      resources :reports, controller: "global_moderations/reports", only: [:index, :show]
    end

    resources :conflicts, only: [:index, :edit, :update], controller: "conflicts"

    root to: "dashboard#show"
  end
end

rails/decidim/decidim-admin/app/controllers/decidim/admin/newsletter_templates_controller.rb
# frozen_string_literal: true

module Decidim
  module Admin
    # Controller that allows managing newsletters.
    class NewsletterTemplatesController < Decidim::Admin::ApplicationController
      helper_method :templates, :template_manifest

      layout "decidim/admin/newsletters"

      def index
        enforce_permission_to :index, :newsletter
      end

      def show; end

      def preview
        email = NewsletterMailer.newsletter(current_user, fake_newsletter)
        Premailer::Rails::Hook.perform(email)
        render html: email.html_part.body.decoded.html_safe
      end

      private

      def templates
        @templates ||= Decidim.content_blocks.for(:newsletter_template)
      end

      def template_manifest
        @template_manifest ||= Decidim
                               .content_blocks
                               .for(:newsletter_template)
                               .find { |manifest| manifest.name.to_s == params[:id] }
      end

      def fake_newsletter
        @fake_newsletter ||= Decidim::Admin::FakeNewsletter.new(current_organization, template_manifest)
      end
    end
  end
end

rails/decidim/decidim-admin/app/views/decidim/admin/newsletter_templates/index.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title">
      <%= t ".title" %>
    </h2>
  </div>

  <div class="card-section">
    <div class="grid-x grid-margin-x card-grid">
    <% templates.each do |newsletter_template| %>
      <div class="cell small-6">
        <div class="card card--mini" id="<%= newsletter_template.name %>">
          <iframe src="<%= preview_newsletter_template_path(newsletter_template.name) %>" class="email-preview newsletter-template-preview">
          </iframe>

          <div class="card-footer">
            <h2 class="card-title">
              <%= t newsletter_template.public_name_key %>
              <%= link_to(t(".preview_template"), newsletter_template_path(newsletter_template.name), class: "button tiny button--title") %>
              <%= link_to(t(".use_template"), new_newsletter_template_newsletter_path(newsletter_template.name), class: "button tiny button--title") %>
            </h2>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>

rails/decidim/decidim-admin/app/views/decidim/admin/newsletter_templates/show.html.erb
<div class="card">
  <div class="card-divider">
    <h2 class="card-title"><%= t ".preview", template_name: t(template_manifest.public_name_key) %></h2>
  </div>
  <div class="card-section">
    <iframe src="<%= preview_newsletter_template_path(template_manifest.name) %>" class="email-preview">
    </iframe>
  </div>
</div>
<div class="button--double form-general-submit">
  <%= link_to(t(".use_template"), new_newsletter_template_newsletter_path(template_manifest.name), class: "button") %>
</div>